config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :dashboard, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  get 'team', to: 'static_pages#team'
  get 'careers', to: 'static_pages#careers'
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end
  resources :lessons, only: [:show]
  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [:update] do
      resources :lessons, only: [:create]
    end
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create] 
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user
  has_many :sections
  has_many :enrollments
  mount_uploader :image, ImageUploader

  validates :title, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}

  def free?
    cost.zero?
  end

  def premium?
    ! free?
  end
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :section
  mount_uploader :video, VideoUploader

  include RankedModel
  ranks :row_order, with_same: :section_id

  def next_lesson
    lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first
    if lesson.blank? && section.next_section
      return section.next_section.lessons.rank(:row_order).first
    end
    return lesson
  end
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  has_many :lessons

  include RankedModel
  ranks :row_order, with_same: :course_id

  def next_section
    section = course.sections.where("row_order > ?", self.row_order).rank(:row_order).first
    return section
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :courses
  has_many :enrollments
  has_many :enrolled_courses, through: :enrollments, source: :course

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def enrolled_in?(course)
    return enrolled_courses.include?(course)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end
  
  def show
    @course = Course.find(params[:id])
  end
  
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  
  def show
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!

  def create
    if current_course.premium?
      # Amount in cents
      @amount = (current_course.cost * 100).to_i

      customer = Stripe::Customer.create(
        email: params[:stripeEmail],
        source: params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        customer: customer.id,
        amount: @amount,
        description: 'Flixter Premo Content',
        currency: 'usd'
      )
    end
    

    current_user.enrollments.create(course: current_course)
    redirect_to course_path(current_course)
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to root_path
    end

  private
  
  def current_course
     @current_course ||= Course.find(params[:course_id])
  end
    
  
end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:show]

  def new
    @course = Course.new
  end
  
  def create
    @course = current_user.courses.create(course_params)
    if @course.valid?
      redirect_to instructor_course_path(@course)
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def show
    @section = Section.new
    @lesson = Lesson.new
  end

  private
    def require_authorized_for_current_course
      if current_course.user != current_user
        return render text: 'Unauthorized', status: :unauthorized
      end
    end
    
    helper_method :current_course
    def current_course
      @current_course = Course.find(params[:id])
    end
    
    def course_params
      params.require(:course).permit(:title, :description, :cost, :image)
    end
  
end

app/controllers/instructor/lessons_controller.rb
class Instructor::LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_section, only: [:create]
   before_action :require_authorized_for_current_lesson, only: [:update]
  
  def create
    @lesson = current_section.lessons.create(lesson_params)
    redirect_to instructor_course_path(current_section.course)
  end

  def update
    current_lesson.update_attributes(lesson_params)
    render text: 'updated!'
  end

  private
  def require_authorized_for_current_lesson
    if current_lesson.section.course.user != current_user
      render text: 'Unauthorized', status: :unauthorized
    end
  end

  def current_lesson
    current_lesson ||= Lesson.find(params[:id])
  end

  def require_authorized_for_current_section
    if current_section.course.user != current_user
      return render text: 'Unauthorized', status: :unauthorized
    end
  end

  helper_method :current_section
  def current_section
    current_section ||= Section.find(params[:section_id])
  end

  def lesson_params
    params.require(:lesson).permit(:title, :subtitle, :video, :row_order_position)
  end
end

app/controllers/instructor/sections_controller.rb
class Instructor::SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:create]
  before_action :require_authorized_for_current_section, only: [:update]
  
  def create
    @section = current_course.sections.create(section_params)
    redirect_to instructor_course_path(current_course)
  end

  def update
    current_section.update_attributes(section_params)
    render text: 'Updated!'
  end

  private
  def require_authorized_for_current_section
    if current_section.course.user != current_user
      render text: 'Unauthorized', status: :unauthorized
    end
  end

  def current_section
    current_section ||= Section.find(params[:id])
  end

  def require_authorized_for_current_course
    if current_course.user != current_user
      return render text: 'Unauthorized', status: :unauthorized
    end
  end
  
  helper_method :current_course
  def current_course
    @current_course ||= Course.find(params[:course_id])
  end
  
  def section_params
    params.require(:section).permit(:title, :row_order_position)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_enrollment_for_current_course, only: [:show]

  def show
  end
 
  private
    def require_enrollment_for_current_course
      if !current_user.enrolled_in?(current_lesson.section.course)
        redirect_to course_url(current_lesson.section.course), alert: "You Aren’t Enrolled"
      end
    end

    helper_method :current_lesson
    def current_lesson
      @current_lesson ||= Lesson.find(params[:id])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end
  
  def privacy
  end
  
  def team
  end

  def careers
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/instructor/sections_helper.rb
module Instructor::SectionsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/courses/index.html.erb
<div id="course-title">
  <div class="row align-middle">
    <div class="small-12 large-10 large-offset-1 columns">
      <div class="row align-middle">
        <div class="small-12 columns">
          <h1>Learn about something today.</h1>
          <p class="lead">Enroll in a class and level up your development skills.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="small-12 large-10 large-offset-1 columns">
      <% @courses.each do |course| %>
      <div class="card">
        <div class="row">
          <div class="small-12 medium-4 columns">
            <%= image_tag course.image %>
          </div>
          <div class="small-12 medium-8 columns card-content">
            <h2><%= link_to course.title, course_path(course) %></h2>
            <p class="lead"><%= course.description %></p>
            <%= link_to 'More Details', course_path(course), class: 'button' %>
          </div>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/courses/show.html.erb
<div id="course-title">
  <div class="row align-middle">
    <div class="small-12 large-10 large-offset-1 columns">
      <div class="row align-middle">
        <div class="small-12 medium-7 columns">
          <h1><%= @course.title %></h1>
          <p class="lead"><%= @course.description %></p>
          <p>
            <% if current_user && current_user == @course.user %>
              <%= link_to 'Administer', instructor_course_path(@course), class: 'button button-white-secondary' %>
            <% end %>
             <% if current_user %>
              <% if current_user.enrolled_in?(@course) %>
                <h3>You Are Enrolled!</h3>
              <% else %>
                <% if @course.free? %>
                  <%= link_to 'Enroll', course_enrollments_path(@course), class: 'button', method: :post %>
                <% else %>
                    <%= form_tag course_enrollments_path(@course) do %>
                      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                              data-email="<%= current_user.email %>"
                              data-description="<%= @course.title %> (<%= number_to_currency @course.cost %>)"
                              data-amount="<%= (@course.cost * 100).to_i %>"
                              data-locale="auto"></script>
                    <% end %>
                  <% end %>
                <% end %>
              <% else %>
                <h5 class="callout warning">Log In to Enroll!</h5>
            <% end %>
          </p>
        </div>
        <div id="course-image" class="small-12 medium-5 columns">
          <%= image_tag @course.image, class: 'feature-image' %>
          <div class="cost">
            <%= number_to_currency @course.cost %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="small-12 large-10 large-offset-1 columns">
    <% @course.sections.rank(:row_order).each do |section| %>
      <br />
      <div class="section">
          <h3><%= section.title %></h3>
          <div class="row">
            <% section.lessons.rank(:row_order).each do |lesson| %>
                <div class="lessons small-12 medium-6 columns">
                  <%= link_to lesson_path(lesson) do %>
                  <div class="card card-content">
                    <h4><%= lesson.title %></h4>
                    <p><%= lesson.subtitle %></p>
                  </div>
                  <% end %>
                </div>
            <% end %>
          </div>
      </div>
    <% end %>
  </div>
</div>

app/views/instructor/courses/new.html.erb
<div class="row">
  <div class="card small-12 large-10 large-offset-1 columns">
    <h1>Add a new course</h1>
    <%= simple_form_for @course, url: instructor_courses_path do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :cost %>
      <%= f.input :image %>

      <%= f.submit 'Create', class: 'button' %>
    <% end %>
  </div>
</div>

app/views/instructor/courses/show.html.erb
<div id="course-title">
  <div class="row align-middle">
    <div class="small-12 large-10 large-offset-1 columns">
      <div class="row align-middle">
        <div class="small-12 medium-7 columns">
          <h1><%= current_course.title %></h1>
          <p class="lead"><%= current_course.description %></p>
          <p>
            <%= link_to 'Preview as Student', course_path(current_course), class: 'button button-white-secondary shrink columns' %>
          </p>
        </div>
        <div id="course-image" class="small-12 medium-5 columns">
          <%= image_tag current_course.image, class: 'feature-image' %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row align-bottom">
  <div class="small-12 large-10 large-offset-1 columns">
    <br />
      <h2>Sections <a data-open="newSectionModal" class="button new-section-button">Add a New Section</a></h2>
      <hr />
  </div>
</div>

<div class="row">
  <div class="small-12 large-10 large-offset-1 columns">
     <div class="row">
       <div class="columns">
        <div class="sections">
          <% current_course.sections.rank(:row_order).each do |section| %>
            <div class="section card card-content" data-update-url=<%= instructor_section_path(section) %>>
               <h3><%= fa_icon "sort" %> <%= section.title %></h3>
              
              <br />
              <ul class="lessons">
                <% section.lessons.rank(:row_order).each do |lesson| %>
                  <li data-update-url=<%= instructor_lesson_path(lesson) %>>
                    <%= fa_icon "sort" %>&nbsp;&nbsp;<strong><%= lesson.title %>:</strong> <%= lesson.subtitle %>
                  </li>
                <% end %>
                <li><a data-open="newLessonModal" class="button new-lesson-button" data-target="#newLessonModal" data-lesson-url="<%= instructor_section_lessons_path(section) %>">Add a New Lesson</a></li>
              </ul>
              
            </div>
          <% end %>
        </div>
      </div>
  </div>
</div>

<div class="reveal" id="newSectionModal" data-reveal>
  <h1>Add a New Section.</h1>
  <%= simple_form_for @section, url: instructor_course_sections_path(current_course) do |f| %>
    <%= f.input :title %>
    <br />
    <%= f.submit 'Add a section', class: 'button' %>
  <% end %>
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="reveal" id="newLessonModal" data-reveal>
  <h1>Add a new lesson.</h1>
  <%= simple_form_for @lesson, url: '#', html: {id: 'newLessonForm' } do |f| %>
    <%= f.input :title %>
    <%= f.input :subtitle %>
    <%= f.input :video %>
    <br />
    <%= f.submit 'Add the lesson', class: 'button' %>
    <br />
  <% end %>
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>


<script>
  $(function(){
    $('.new-lesson-button').click(function(event) {
      var lessonUrl = $( event.target ).data('lesson-url');
      $('#newLessonForm').attr('action', lessonUrl);
    });

    $('.sections').sortable({
      update: function( event, ui ){
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json',
          data: { section: { row_order_position: ui.item.index() } }
        });
      }
    });

    $('.lessons').sortable({
      update: function( event, ui ){
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json',
          data: { lesson: { row_order_position: ui.item.index() } }
        });
      }
    });
  });
</script>

app/views/lessons/show.html.erb
<div id="course-title">
  <div class="row align-middle">
    <div class="small-12 large-10 large-offset-1 columns">
      <div class="row align-middle">
        <div class="small-12 medium-8 columns">
          <h1><%= current_lesson.section.course.title %></h1>
          <p class="lead"><strong><%= current_lesson.title %></strong></p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="small-12 large-10 large-offset-1 columns">
    <div class="card video-card">
      <div class="responsive-embed">
        <video id="my-video" class="video-js vjs-big-play-centered vjs-fluid" controls preload="auto" width="auto" height="auto"
        poster="<%= image_path('black.gif') %>" data-setup="{}">
          <source src="<%= current_lesson.video.to_s %>" type='video/mp4'>
          <noscript>
            <p class="vjs-no-js">
              To view this video please enable JavaScript, and consider upgrading to a web browser that
              <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
            </p>
          </noscript>
        </video>
        <div class="card-content">
          <h2><%= current_lesson.title %></h2>
          <p class="float-left"><%= current_lesson.subtitle %></p>
           <% if current_lesson.next_lesson.present? %>
            <%= link_to lesson_path(current_lesson.next_lesson), class: 'button float-right' do %>
            Next Lesson
            <%= fa_icon "arrow-right" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>