config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :dashboard, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  get 'team', to: 'static_pages#team'
  get 'careers', to: 'static_pages#careers'
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end
  resources :lessons, only: [:show]
  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [:update] do
      resources :lessons, only: [:create]
    end
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create] 
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user
  has_many :sections
  has_many :enrollments
  mount_uploader :image, ImageUploader

  validates :title, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}

  def free?
    cost.zero?
  end

  def premium?
    ! free?
  end
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :section
  mount_uploader :video, VideoUploader

  include RankedModel
  ranks :row_order, with_same: :section_id

  def next_lesson
    lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first
    if lesson.blank? && section.next_section
      return section.next_section.lessons.rank(:row_order).first
    end
    return lesson
  end
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  has_many :lessons

  include RankedModel
  ranks :row_order, with_same: :course_id

  def next_section
    section = course.sections.where("row_order > ?", self.row_order).rank(:row_order).first
    return section
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :courses
  has_many :enrollments
  has_many :enrolled_courses, through: :enrollments, source: :course

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def enrolled_in?(course)
    return enrolled_courses.include?(course)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end
  
  def show
    @course = Course.find(params[:id])
  end
  
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  
  def show
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!

  def create
    if current_course.premium?
      # Amount in cents
      @amount = (current_course.cost * 100).to_i

      customer = Stripe::Customer.create(
        email: params[:stripeEmail],
        source: params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        customer: customer.id,
        amount: @amount,
        description: 'Flixter Premo Content',
        currency: 'usd'
      )
    end
    

    current_user.enrollments.create(course: current_course)
    redirect_to course_path(current_course)
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to root_path
    end

  private
  
  def current_course
     @current_course ||= Course.find(params[:course_id])
  end
    
  
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_enrollment_for_current_course, only: [:show]

  def show
  end
 
  private
    def require_enrollment_for_current_course
      if !current_user.enrolled_in?(current_lesson.section.course)
        redirect_to course_url(current_lesson.section.course), alert: "You Aren’t Enrolled"
      end
    end

    helper_method :current_lesson
    def current_lesson
      @current_lesson ||= Lesson.find(params[:id])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end
  
  def privacy
  end
  
  def team
  end

  def careers
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "DevStream" %></title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    "application" %>
    <link href="https://vjs.zencdn.net/5.12.6/video-js.css" rel="stylesheet">
    <script src="https://use.typekit.net/vuz1bcr.js"></script>
    <script>try{Typekit.load({ async: true });}catch(e){}</script>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  </head>

  <body>
    <nav>
      <div class="top-bar">
        <div class="row">
            <div class="expand columns">
              <ul class="menu">
                <li><%= link_to root_path, class: 'menu-text', id: 'logo' do %>
                      &lt;DevStream&gt;
                    <% end %>
                </li>
                <li class="show-for-medium"><%= link_to 'See All Courses', courses_path %></li>
              </ul>
            </div>
            <div class="shrink columns right-nav">
              <ul class="menu">
                <% if user_signed_in? %>
                  <li><%= link_to 'My Dashboard', dashboard_path %></li>
                  <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'button' %></li>
                <% else %>
                  <li><%= link_to 'Log In', new_user_session_path %></li>
                  <li><%= link_to 'Sign Up', new_user_registration_path, class: 'button' %></li>
                <% end %>
              </ul>
            </div>
        </div>
      </div>
    </nav>

    <% if notice.present? %>
      <p class="callout primary text-center"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="callout alert text-center"><%= alert %></p>
    <% end %>
    <section class="content">
      <%= yield %>
    </section>
    <footer class="footer">
      <div class="row">
        <div class="small-12 medium-6 large-3 columns">
          <strong>Teachers</strong>
          <div>
            <%= link_to 'Teach a Course', new_instructor_course_path %>
          </div>
          <div>
            <%= link_to 'My Dashboard', dashboard_path %>
          </div>
        </div>
        <div class="small-12 medium-6 large-3 columns">
          <strong>About</strong>
          <div>
            <%= link_to 'Team', team_path %>
          </div>
          <div>
            <%= link_to 'Careers', careers_path %>
          </div>
          <div>
            <%= link_to 'Privacy Policy', privacy_path %>
          </div>
        </div>
        <div class="small-12 medium-6 large-3 columns">
          <strong>Contact</strong>
          <div>
            <%= link_to 'contact@justinmunn.co', 'mailto:contact@justinmunn.co' %>
          </div>
          <div>
            Seattle, WA
          </div>
        </div>
        <div class="small-12 medium-6 large-3 columns">
          <strong>Social</strong>
          <div id="social-footer">
            <%= link_to "https://github.com/jwmunn" do %>
              <%= fa_icon "github-square", class: "fa-2x social-button" %>
            <% end %>
            <%= link_to "https://twitter.com/jwmunn" do %>
              <%= fa_icon "twitter-square", class: "fa-2x social-button" %>
            <% end %>
            <%= link_to "https://www.linkedin.com/in/jwmunn/" do %>
              <%= fa_icon "linkedin-square", class: "fa-2x social-button" %>
            <% end %>
          </div>
        </div>
      </div>
    </footer>
    <script src="https://vjs.zencdn.net/5.12.6/video.js"></script>
    <script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
    <script>
      $(function(){ $(document).foundation(); });
    </script>
  </body>
</html>